spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heima?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    #    url: jdbc:mysql://localhost:3306/health-heimaxx
    username: root
    password: root
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379


#mybatis-plus
mybatis-plus:
  type-aliases-package: com.itheima.pojo
  configuration:
    #   sql日志显示，这里使用标准显示
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #  数据库中如果有类似 如  user_name 等命名，会将 _后的字母大写，这里是为了和实体类对应
    map-underscore-to-camel-case: true
pagehelper:
  auto-dialect: mysql
