server:
  port: 8088
#加载子模块yml配置
spring:
  profiles:
    include: mapper

      #spring:
      #profiles:
    #active: redis

dubbo:
  application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
    name: dubbo_provider
  registry:                 #注册中心配置，用于配置连接注册中心相关信息。
    address: zookeeper://127.0.0.1:2181
  protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
    name: dubbo
    port: 20881
  version: 1.0
  scan:
    base-packages: com.itheima.service.impl  #服务暴露与发现消费所在的package